spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: myDataBase
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    serializer: org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer
    jedis:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 10
        max-wait: 2000


# Mostrar Queries MongoDB no Terminal:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG