spring:
  application:
    name: eureka-client-logs
  data:
    mongodb:
      port: 27017
      host: localhost
      database: myCompany
  rabbitmq:
    addresses: amqps://user:password@shrimp.rmq.cloudamqp.com/gzptufek
    queue: softwareHouse.queue
#  rabbitmq:
#    host: shrimp.rmq.cloudamqp.com
#    port: 5672
#    username: gzptufek
#    password: KyF3Nza05dD7weDpskEQVU5sIIq-huHe

# Configuracao da porta do serviço de forma aleatoria
server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# RabbitMQ - Variaveis de ambiente customizadas
softwareHouse:
  rabbitmq:
    exchange: softwareHouse.exchange
    rountingkey: softwareHouse.employee.routingkey
    queue: softwareHouse.queue

# Mostrar Queries MongoDB no Terminal:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG